# Прозрачность
background_opacity 0.85

# Убираем рамки и заголовок окна
hide_window_decorations yes

# Шрифт
font_family JetBrainsMono Nerd Font
font_size 11

# Курсор
cursor_shape block
cursor_blink_interval 0

# Убираем задержку при старте
repaint_delay 10
input_delay 3
sync_to_monitor yes
